### ISSUE TITLE
Attempting to render .qmd with python3 kernel

### ISSUE THREAD

**Issue by jack-fletch** [quarto-dev/quarto-vscode#67] opened 2022-08-26 04:35 UTC
Hi, when trying to render .qmd file with a python3 kernel, I am getting an error `ERROR: NotFound: The system cannot find the file specified. (os error 2)`. 

Ran `quarto check` and everything seems to be in order (namely, the kernel is being picked up and jupyter rendering seems to check out): 
`[>] Checking Python 3 installation....OK`
     ` Version: 3.10.0
      Path: C:/Users/../AppData/Local/Programs/Python/Python310/python.exe`
      `Jupyter: 4.9.1`
     `Kernels: python3`  

`[>] Checking Jupyter engine render....OK`

Here is my `.qmd`:

---
title: "another_test"
format: html
jupyter: python3
---

```{python}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(
  subplot_kw = {'projection': 'polar'} 
)
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
````

I am on v1.33.0 for the vscode extension and v1.0.38 for quarto itself. (and am using a windows machine).
Any help you could provide would be greatly appreciated.

**Comment by jjallaire** [comment] 2022-08-26 11:23
A couple things we can try:

(1) Update to to the current pre-release of Quarto v1.1 which may fix the problem: https://quarto.org/docs/download/prerelease.html

(2) Try setting the `QUARTO_PRINT_STACK` environment variable before rendering to so we can see exactly where the problem is occurring:

```bash
setx QUARTO_PRINT_STACK "true"
```

**Comment by jack-fletch** [comment] 2022-08-26 14:47
Thanks for getting back to me. When I upgrade to v1.1, I now get a strange VScode popup saying:

![image](https://user-images.githubusercontent.com/85920658/186926926-78f8d66b-9b13-4694-ae3f-457374fcc2b0.png)

Logs say: 
`[2022-08-26 07:31:24.579] [exthost] [error] TypeError: Invalid Version: [1mquarto[22m [34m1.1.132
[39m`

I noticed this issue yesterday when troubleshooting (which is why I stuck with 1.0.38). 

Continuing on with 1.038:

Unfortunately, even after setting the environment variable like you suggested and still don't get any more information when rendering other than that error message. 

`PS P:\Repo\..\scoping> setx QUARTO_PRINT_STACK "true"`
`SUCCESS: Specified value was saved.`
`PS P:\Repo\..\scoping> quarto render another_test.qmd`                                              
`ERROR: NotFound: The system cannot find the file specified. (os error 2)`
`PS P:\Repo\..\scoping>`

**Comment by jjallaire** [comment] 2022-08-26 18:19
We just fixed this "Invalid Version" issue in Quarto 1.1.140 (just released a couple of hours ago): https://quarto.org/docs/get-started/

Try that and you should get the stack trace w/ `QUARTO_PRINT_STACK`

**Comment by jack-fletch** [comment] 2022-08-26 18:36
Wonderful, i get the print out now:

`ERROR: NotFound: The system cannot find the file specified. (os error 2)`

`NotFound: The system cannot find the file specified. (os error 2)`
   `at Object.opSync (deno:core/01_core.js:172:12)`
    `at Object.realPathSync (deno:runtime/js/30_fs.js:139:17)`
    `at kernelTransportFile (file:///C:/Users/../AppData/Local/Programs/Quarto/bin/quarto.js:28394:29)`   
    `at connectToKernel (file:///C:/Users/../AppData/Local/Programs/Quarto/bin/quarto.js:28437:27)`       
    `at executeKernelKeepalive (file:///C:/Users/../AppData/Local/Programs/Quarto/bin/quarto.js:28238:37)`
    `at Object.execute (file:///C:/Users/../AppData/Local/Programs/Quarto/bin/quarto.js:29007:23)`        
    `at async renderExecute (file:///C:/Users/../AppData/Local/Programs/Quarto/bin/quarto.js:76312:27)`   
    `at async renderFiles (file:///C:/Users/../AppData/Local/Programs/Quarto/bin/quarto.js:76417:47)`     
    `at async render (file:///C:/Users/../AppData/Local/Programs/Quarto/bin/quarto.js:76785:20)`
    `at async renderForPreview (file:///C:/Users/../AppData/Local/Programs/Quarto/bin/quarto.js:87450:26)`

**Comment by jjallaire** [comment] 2022-08-26 18:51
This is a real mystery to me! This is basically saying that the ipynb file that we generate alongside the qmd does not exist (but as far as I can see the code right prior to this always creates it). Perhaps there is something to do with relative/absolute paths going on in our code?

Some additional details it would be good to have:

1) Are you executing a standalone qmd file or are you executing one within a project?

2) After the error occurs, can you try `dir` to see if the qmd and the ipynb are both in the current working directory?

3) I think this will be resolved if you add:

```yaml
execute:
  daemon: false
```

We don't really want that to be the solution though as you'd be giving up having a persistent jupyter kernel (would just be good to know if it does indeed clear the problem)

**Comment by jack-fletch** [comment] 2022-08-26 19:20
1. I am within a project/folder in vscode. I created a standalone .qmd and tried to render.
2. I see the ipynb in the folder after the run fails.

When i add the `daemon: false` setting, the kernel starts up but now i see:
`Starting python3 kernel...`

`[WinError 3] The system cannot find the path specified: 'UNC\\x.org\\RPON\\xx\\Userdir04\\..\\Repo\\..\\scoping'
PS P:\Repo\..\scoping> `

Interestingly, I switched to a folder outside of my organizations network drive (to my c drive) and all of these issues completely disappear and I am able to run everything as expected.

It may also be worth bringing up another error I get when trying to render HTML/PDF, namely an "Internal Server Error" (500). Similar to https://www.reddit.com/r/RStudio/comments/voinx2/rstudio_quarto_document_not_displaying_in_viewer/. This error also goes away when I run locally on C drive rather than company network. Not sure if these issues are related. If you need additional information let me know.

**Comment by jjallaire** [comment] 2022-08-26 19:57
Now we are getting somewhere! There is likely a problem w/ UNC paths we need to work through.

Could you create a file named `test.ts` in the same directory as your qmd:

```typescript
console.log(Deno.cwd());
console.log(Deno.realPathSync("."));
```

Then run it as follows (from that directory):

```bash
quarto run test.ts
```

**Comment by jack-fletch** [comment] 2022-08-26 20:21
Sure thing.

`PS P:\Repo\..\scoping> quarto run test.ts`
`P:\Repo\..\scoping`
`UNC\x.org\RPON\..\Userdir04\..\Repo\..\scoping`
`Check file:///P:/Repo/../scoping/test.ts`
`PS P:\Repo\..\scoping>`

**Comment by jjallaire** [comment] 2022-08-26 20:25
how about if you modify the `test.ts` file to use the ipynb rather than "." as its target?

**Comment by jack-fletch** [comment] 2022-08-26 20:29
that check didnt work: 
`P:\Repo\..\scoping
Check file:///P:/Repo/../scoping/test.ts
error: Uncaught NotFound: The system cannot find the file specified. (os error 2)
console.log(Deno.realPathSync("ipynb"));
                 ^
    at Object.opSync (deno:core/01_core.js:172:12)
    at Object.realPathSync (deno:runtime/js/30_fs.js:139:17)
    at file:///P:/Repo/../scoping/test.ts:2:18
PS P:\Repo\..\scoping> `

**Comment by jjallaire** [comment] 2022-08-26 20:40
Bingo! Working on a fix right now.

**Comment by jjallaire** [comment] 2022-08-26 20:46
Could you run this version of the script:

```typescript
console.log(Deno.cwd());
console.log(Deno.realPathSync(Deno.cwd());
```

**Comment by jack-fletch** [comment] 2022-08-26 21:26
`PS P:\Repo\..\scoping> quarto run test.ts`
`P:\Repo\..\scoping`
`UNC\x.org\RPON\NASP001\Userdir04\..\Repo\..\scoping`
`Check file:///P:/Repo/../scoping/test.ts`
`PS P:\Repo\..\scoping> `

**Comment by jjallaire** [comment] 2022-08-26 22:57
I've attempted a fix for this (basically emulating the Deno.realPathSync function on Windows so we don't run into the UNC issues). You can try it out by downloading our v1.2.15 pre-release from here: https://quarto.org/docs/download/prerelease.html

**Comment by jack-fletch** [comment] 2022-08-26 23:05
Success! Everything seems to be working as expected now. Onward!

**Comment by jjallaire** [comment] 2022-08-26 23:14
Fantastic! Thanks so much for bearing with me in tracking this down.

**Closed by jjallaire** 2022-08-26 23:14 UTC
